<a href="https://colab.research.google.com/github/jee365/ESAA/blob/main/wine_Exercises_ipynb_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Wine

### Introduction:

This exercise is a adaptation from the UCI Wine dataset.
The only pupose is to practice deleting data with pandas.

### Step 1. Import the necessary libraries

In [18]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data).

In [4]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

### Step 3. Assign it to a variable called wine

In [24]:
wine= pd.read_table('/content/gdrive/My Drive/Colab Notebooks/wine.txt',sep=',',header=None)
wine.head()

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [25]:
wine.drop(wine.columns[[0,3,6,8,10,12,13]],axis=1,inplace=True)
wine.head()

      1     2     4    5     7     9     11
0  14.23  1.71  15.6  127  3.06  2.29  1.04
1  13.20  1.78  11.2  100  2.76  1.28  1.05
2  13.16  2.36  18.6  101  3.24  2.81  1.03
3  14.37  1.95  16.8  113  3.49  2.18  0.86
4  13.24  2.59  21.0  118  2.69  1.82  1.04

### Step 5. Assign the columns as below:

The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [26]:
wine.columns=['alcohol','malic_acid','alcalinity_of_ash','magnesium','flavanoids','proanthocyanins','hue']
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,14.23,1.71,15.6,127,3.06,2.29,1.04
1,13.20,1.78,11.2,100,2.76,1.28,1.05
2,13.16,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86
4,13.24,2.59,21.0,118,2.69,1.82,1.04

### Step 6. Set the values of the first 3 rows from alcohol as NaN

In [27]:
wine['alcohol'].iloc[0:3]=np.NAN
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127,3.06,2.29,1.04
1,NaN,1.78,11.2,100,2.76,1.28,1.05
2,NaN,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86
4,13.24,2.59,21.0,118,2.69,1.82,1.04

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [28]:
wine['magnesium'].iloc[2:4]=np.NAN
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,NaN,3.24,2.81,1.03
3,14.37,1.95,16.8,NaN,3.49,2.18,0.86
4,13.24,2.59,21.0,118.0,2.69,1.82,1.04

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [30]:
wine['alcohol']=wine['alcohol'].fillna(10)
wine['magnesium']=wine['magnesium'].fillna(100)

wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.71,15.6,127.0,3.06,2.29,1.04
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
2,10.00,2.36,18.6,100.0,3.24,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
4,13.24,2.59,21.0,118.0,2.69,1.82,1.04

### Step 9. Count the number of missing values

In [32]:
wine.isnull().sum()

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 10.  Create an array of 10 random numbers up until 10

In [34]:
num=np.random.randint(0,11,10)
num

array([ 4, 10,  8,  6,  6,  4,  0,  1,  7,  7])

### Step 11.  Use random numbers you generated as an index and assign NaN value to each of cell.

In [38]:
wine['alcohol'].iloc[num]=np.NAN
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,10.00,2.36,18.6,100.0,3.24,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
4,NaN,2.59,21.0,118.0,2.69,1.82,1.04
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
6,NaN,1.87,14.6,96.0,2.52,1.98,1.02
7,NaN,2.15,17.6,121.0,2.51,1.25,1.06
8,NaN,1.64,14.0,97.0,2.98,1.98,1.08
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
10,NaN,2.16,18.0,105.0,3.32,2.38,1.25
11,14.12,1.48,16.8,95.0,2.43,1.57,1.17
12,13.75,1.73,16.0,89.0,2.76,1.81,1.15
13,14.75,1.73,11.4,91.0,3.69,2.81,1.25
14,14.38,1.87,12.0,102.0,3.64,2.96,1.20
15,13.63,1.81,17.2,112.0,2.91,1.46,1.28
16,14.30,1.92,20.0,120.0,3.14,1.97,1.07
17,13.83,1.57,20.0,115.0,3.40,1.72,1.13
18,14.19,1.59,16.5,108.0,3.93,1.86,1.23
19,13.64,3.10,15.2,116.0,3.03,1.66,0.96
20,14.06,1.63,16.0,126.0,3.17,2.10,1.09
21,12.93,3.80,18.6,102.0,2.41,1.98,1.03
22,13.71,1.86,16.6,101.0,2.88,1.69,1.11
23,12.85,1.60,17.8,95.0,2.37,1.46,1.09
24,13.50,1.81,20.0,96.0,2.61,1.66,1.12
25,13.05,2.05,25.0,124.0,2.68,1.92,1.13
26,13.39,1.77,16.1,93.0,2.94,1.45,0.92
27,13.30,1.72,17.0,94.0,2.19,1.35,1.02
28,13.87,1.90,19.4,107.0,2.97,1.76,1.25
29,14.02,1.68,16.0,96.0,2.33,1.98,1.04
...,...,...,...,...,...,...,...
148,13.32,3.24,21.5,92.0,0.76,1.25,0.55
149,13.08,3.90,21.5,113.0,1.39,1.14,0.57
150,13.50,3.12,24.0,123.0,1.57,1.25,0.59
151,12.79,2.67,22.0,112.0,1.36,1.26,0.48
152,13.11,1.90,25.5,116.0,1.28,1.56,0.61
153,13.23,3.30,18.5,98.0,0.83,1.87,0.56
154,12.58,1.29,20.0,103.0,0.58,1.40,0.58
155,13.17,5.19,22.0,93.0,0.63,1.55,0.60
156,13.84,4.12,19.5,89.0,0.83,1.56,0.57
157,12.45,3.03,27.0,97.0,0.58,1.14,0.67
158,14.34,1.68,25.0,98.0,1.31,2.70,0.57
159,13.48,1.67,22.5,89.0,1.10,2.29,0.57
160,12.36,3.83,21.0,88.0,0.92,1.04,0.56
161,13.69,3.26,20.0,107.0,0.56,0.80,0.96
162,12.85,3.27,22.0,106.0,0.60,0.96,0.87
163,12.96,3.45,18.5,106.0,0.70,0.94,0.68
164,13.78,2.76,22.0,90.0,0.68,1.03,0.70
165,13.73,4.36,22.5,88.0,0.47,1.15,0.78
166,13.45,3.70,23.0,111.0,0.92,1.46,0.85
167,12.82,3.37,19.5,88.0,0.66,0.97,0.72
168,13.58,2.58,24.5,105.0,0.84,1.54,0.74
169,13.40,4.60,25.0,112.0,0.96,1.11,0.67
170,12.20,3.03,19.0,96.0,0.49,0.73,0.66
171,12.77,2.39,19.5,86.0,0.51,0.64,0.57
172,14.16,2.51,20.0,91.0,0.70,1.24,0.62
173,13.71,5.65,20.5,95.0,0.61,1.06,0.64
174,13.40,3.91,23.0,102.0,0.75,1.41,0.70
175,13.27,4.28,20.0,120.0,0.69,1.35,0.59
176,13.17,2.59,20.0,120.0,0.68,1.46,0.60
177,14.13,4.10,24.5,96.0,0.76,1.35,0.61

### Step 12.  How many missing values do we have?

In [39]:
wine.isnull().sum()

alcohol              7
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 13. Delete the rows that contain missing values

In [42]:
wine1=wine.dropna()
wine1

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
2,10.00,2.36,18.6,100.0,3.24,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
11,14.12,1.48,16.8,95.0,2.43,1.57,1.17
12,13.75,1.73,16.0,89.0,2.76,1.81,1.15
13,14.75,1.73,11.4,91.0,3.69,2.81,1.25
14,14.38,1.87,12.0,102.0,3.64,2.96,1.20
15,13.63,1.81,17.2,112.0,2.91,1.46,1.28
16,14.30,1.92,20.0,120.0,3.14,1.97,1.07
17,13.83,1.57,20.0,115.0,3.40,1.72,1.13
18,14.19,1.59,16.5,108.0,3.93,1.86,1.23
19,13.64,3.10,15.2,116.0,3.03,1.66,0.96
20,14.06,1.63,16.0,126.0,3.17,2.10,1.09
21,12.93,3.80,18.6,102.0,2.41,1.98,1.03
22,13.71,1.86,16.6,101.0,2.88,1.69,1.11
23,12.85,1.60,17.8,95.0,2.37,1.46,1.09
24,13.50,1.81,20.0,96.0,2.61,1.66,1.12
25,13.05,2.05,25.0,124.0,2.68,1.92,1.13
26,13.39,1.77,16.1,93.0,2.94,1.45,0.92
27,13.30,1.72,17.0,94.0,2.19,1.35,1.02
28,13.87,1.90,19.4,107.0,2.97,1.76,1.25
29,14.02,1.68,16.0,96.0,2.33,1.98,1.04
30,13.73,1.50,22.5,101.0,3.25,2.38,1.19
31,13.58,1.66,19.1,106.0,3.19,1.95,1.09
32,13.68,1.83,17.2,104.0,2.69,1.97,1.23
33,13.76,1.53,19.5,132.0,2.74,1.35,1.25
34,13.51,1.80,19.0,110.0,2.53,1.54,1.10
35,13.48,1.81,20.5,100.0,2.98,1.86,1.04
36,13.28,1.64,15.5,110.0,2.68,1.36,1.09
...,...,...,...,...,...,...,...
148,13.32,3.24,21.5,92.0,0.76,1.25,0.55
149,13.08,3.90,21.5,113.0,1.39,1.14,0.57
150,13.50,3.12,24.0,123.0,1.57,1.25,0.59
151,12.79,2.67,22.0,112.0,1.36,1.26,0.48
152,13.11,1.90,25.5,116.0,1.28,1.56,0.61
153,13.23,3.30,18.5,98.0,0.83,1.87,0.56
154,12.58,1.29,20.0,103.0,0.58,1.40,0.58
155,13.17,5.19,22.0,93.0,0.63,1.55,0.60
156,13.84,4.12,19.5,89.0,0.83,1.56,0.57
157,12.45,3.03,27.0,97.0,0.58,1.14,0.67
158,14.34,1.68,25.0,98.0,1.31,2.70,0.57
159,13.48,1.67,22.5,89.0,1.10,2.29,0.57
160,12.36,3.83,21.0,88.0,0.92,1.04,0.56
161,13.69,3.26,20.0,107.0,0.56,0.80,0.96
162,12.85,3.27,22.0,106.0,0.60,0.96,0.87
163,12.96,3.45,18.5,106.0,0.70,0.94,0.68
164,13.78,2.76,22.0,90.0,0.68,1.03,0.70
165,13.73,4.36,22.5,88.0,0.47,1.15,0.78
166,13.45,3.70,23.0,111.0,0.92,1.46,0.85
167,12.82,3.37,19.5,88.0,0.66,0.97,0.72
168,13.58,2.58,24.5,105.0,0.84,1.54,0.74
169,13.40,4.60,25.0,112.0,0.96,1.11,0.67
170,12.20,3.03,19.0,96.0,0.49,0.73,0.66
171,12.77,2.39,19.5,86.0,0.51,0.64,0.57
172,14.16,2.51,20.0,91.0,0.70,1.24,0.62
173,13.71,5.65,20.5,95.0,0.61,1.06,0.64
174,13.40,3.91,23.0,102.0,0.75,1.41,0.70
175,13.27,4.28,20.0,120.0,0.69,1.35,0.59
176,13.17,2.59,20.0,120.0,0.68,1.46,0.60
177,14.13,4.10,24.5,96.0,0.76,1.35,0.61

### Step 14. Print only the non-null values in alcohol

In [44]:
wine2=wine['alcohol'].dropna()
wine2

2      10.00
3      14.37
5      14.20
9      13.86
11     14.12
12     13.75
13     14.75
14     14.38
15     13.63
16     14.30
17     13.83
18     14.19
19     13.64
20     14.06
21     12.93
22     13.71
23     12.85
24     13.50
25     13.05
26     13.39
27     13.30
28     13.87
29     14.02
30     13.73
31     13.58
32     13.68
33     13.76
34     13.51
35     13.48
36     13.28
       ...
148    13.32
149    13.08
150    13.50
151    12.79
152    13.11
153    13.23
154    12.58
155    13.17
156    13.84
157    12.45
158    14.34
159    13.48
160    12.36
161    13.69
162    12.85
163    12.96
164    13.78
165    13.73
166    13.45
167    12.82
168    13.58
169    13.40
170    12.20
171    12.77
172    14.16
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: alcohol, Length: 171, dtype: float64

### Step 15.  Reset the index, so it starts with 0 again

In [50]:
wine3=wine1.reset_index(drop=True)
wine3

,level_0,index,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,0,2,10.00,2.36,18.6,100.0,3.24,2.81,1.03
1,1,3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
2,2,5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
3,3,9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
4,4,11,14.12,1.48,16.8,95.0,2.43,1.57,1.17
5,5,12,13.75,1.73,16.0,89.0,2.76,1.81,1.15
6,6,13,14.75,1.73,11.4,91.0,3.69,2.81,1.25
7,7,14,14.38,1.87,12.0,102.0,3.64,2.96,1.20
8,8,15,13.63,1.81,17.2,112.0,2.91,1.46,1.28
9,9,16,14.30,1.92,20.0,120.0,3.14,1.97,1.07
10,10,17,13.83,1.57,20.0,115.0,3.40,1.72,1.13
11,11,18,14.19,1.59,16.5,108.0,3.93,1.86,1.23
12,12,19,13.64,3.10,15.2,116.0,3.03,1.66,0.96
13,13,20,14.06,1.63,16.0,126.0,3.17,2.10,1.09
14,14,21,12.93,3.80,18.6,102.0,2.41,1.98,1.03
15,15,22,13.71,1.86,16.6,101.0,2.88,1.69,1.11
16,16,23,12.85,1.60,17.8,95.0,2.37,1.46,1.09
17,17,24,13.50,1.81,20.0,96.0,2.61,1.66,1.12
18,18,25,13.05,2.05,25.0,124.0,2.68,1.92,1.13
19,19,26,13.39,1.77,16.1,93.0,2.94,1.45,0.92
20,20,27,13.30,1.72,17.0,94.0,2.19,1.35,1.02
21,21,28,13.87,1.90,19.4,107.0,2.97,1.76,1.25
22,22,29,14.02,1.68,16.0,96.0,2.33,1.98,1.04
23,23,30,13.73,1.50,22.5,101.0,3.25,2.38,1.19
24,24,31,13.58,1.66,19.1,106.0,3.19,1.95,1.09
25,25,32,13.68,1.83,17.2,104.0,2.69,1.97,1.23
26,26,33,13.76,1.53,19.5,132.0,2.74,1.35,1.25
27,27,34,13.51,1.80,19.0,110.0,2.53,1.54,1.10
28,28,35,13.48,1.81,20.5,100.0,2.98,1.86,1.04
29,29,36,13.28,1.64,15.5,110.0,2.68,1.36,1.09
...,...,...,...,...,...,...,...,...,...
141,141,148,13.32,3.24,21.5,92.0,0.76,1.25,0.55
142,142,149,13.08,3.90,21.5,113.0,1.39,1.14,0.57
143,143,150,13.50,3.12,24.0,123.0,1.57,1.25,0.59
144,144,151,12.79,2.67,22.0,112.0,1.36,1.26,0.48
145,145,152,13.11,1.90,25.5,116.0,1.28,1.56,0.61
146,146,153,13.23,3.30,18.5,98.0,0.83,1.87,0.56
147,147,154,12.58,1.29,20.0,103.0,0.58,1.40,0.58
148,148,155,13.17,5.19,22.0,93.0,0.63,1.55,0.60
149,149,156,13.84,4.12,19.5,89.0,0.83,1.56,0.57
150,150,157,12.45,3.03,27.0,97.0,0.58,1.14,0.67
151,151,158,14.34,1.68,25.0,98.0,1.31,2.70,0.57
152,152,159,13.48,1.67,22.5,89.0,1.10,2.29,0.57
153,153,160,12.36,3.83,21.0,88.0,0.92,1.04,0.56
154,154,161,13.69,3.26,20.0,107.0,0.56,0.80,0.96
155,155,162,12.85,3.27,22.0,106.0,0.60,0.96,0.87
156,156,163,12.96,3.45,18.5,106.0,0.70,0.94,0.68
157,157,164,13.78,2.76,22.0,90.0,0.68,1.03,0.70
158,158,165,13.73,4.36,22.5,88.0,0.47,1.15,0.78
159,159,166,13.45,3.70,23.0,111.0,0.92,1.46,0.85
160,160,167,12.82,3.37,19.5,88.0,0.66,0.97,0.72
161,161,168,13.58,2.58,24.5,105.0,0.84,1.54,0.74
162,162,169,13.40,4.60,25.0,112.0,0.96,1.11,0.67
163,163,170,12.20,3.03,19.0,96.0,0.49,0.73,0.66
164,164,171,12.77,2.39,19.5,86.0,0.51,0.64,0.57
165,165,172,14.16,2.51,20.0,91.0,0.70,1.24,0.62
166,166,173,13.71,5.65,20.5,95.0,0.61,1.06,0.64
167,167,174,13.40,3.91,23.0,102.0,0.75,1.41,0.70
168,168,175,13.27,4.28,20.0,120.0,0.69,1.35,0.59
169,169,176,13.17,2.59,20.0,120.0,0.68,1.46,0.60
170,170,177,14.13,4.10,24.5,96.0,0.76,1.35,0.61

### BONUS: Create your own question and answer it.