<a href="https://colab.research.google.com/github/jee365/ESAA/blob/main/%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. scikit-learn 으로부터 의사결정나무 모듈을 불러오는 코드를 아래에 작성하세요.

In [1]:
from sklearn.tree import DecisionTreeClassifier

# 셀을 실행할 때 팝업이 뜨면 `무시하고 계속하기` 를 눌러주세요
## 데이터 다운로드
--- 
아래 셀을 실행시켜 데이터를 colab에 불러옵니다.  
셀 실행은 Ctrl + Enter 를 이용해 실행 시킬 수 있습니다.

In [2]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3gLj0Q6'

import zipfile
with zipfile.ZipFile('3gLj0Q6', 'r') as existing_zip:
    existing_zip.extractall('data')

--2021-10-11 09:35:32--  https://bit.ly/3gLj0Q6
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E [following]
--2021-10-11 09:35:32--  https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E
Resolving drive.google.com (drive.google.com)... 172.217.203.101, 172.217.203.113, 172.217.203.138, ...
Connecting to drive.google.com (drive.google.com)|172.217.203.101|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0c-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fnckp2r02t9pi3s7ug8cte1c7cr20vkl/1633944900000/17946651057176172524/*/1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E?e=download [following]
Warning: wildcards not supported in HTTP.
--2021-10-11 09:35:33--  https://doc-0c-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fnckp2r02t9pi3s7ug8cte1c7cr20vkl/1633944900000/17946651057176172524/*/1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E?e=download
Resolving doc-0c-10-docs.googleusercontent.com (doc-0c-10-docs.googleusercontent.com)... 74.125.31.132, 2607:f8b0:400c:c02::84
Connecting to doc-0c-10-docs.googleusercontent.com (doc-0c-10-docs.googleusercontent.com)|74.125.31.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39208 (38K) [application/zip]
Saving to: ‘3gLj0Q6’

3gLj0Q6             100%[===================>]  38.29K  --.-KB/s    in 0s

2021-10-11 09:35:33 (115 MB/s) - ‘3gLj0Q6’ saved [39208/39208]

## 라이브러리 불러오기
---
아래 셀을 실행시켜 pandas 와 DecisionTreeClassifier 를 불러옵니다.

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

## 데이터 불러오기
---
아래 셀을 실행시켜 csv 파일 데이터를 DataFrame 객체로 불러옵니다.

In [4]:
train = pd.read_csv('data/train.csv') 
test = pd.read_csv('data/test.csv')

## 결측치 제거하기
---
결측치를 제거하고, 결측치가 모두 제거됐는지 확인합니다.

In [5]:
test = test.dropna()
train = train.dropna()

print(train.isnull().sum())

id                        0
hour                      0
hour_bef_temperature      0
hour_bef_precipitation    0
hour_bef_windspeed        0
hour_bef_humidity         0
hour_bef_visibility       0
hour_bef_ozone            0
hour_bef_pm10             0
hour_bef_pm2.5            0
count                     0
dtype: int64

2. train 데이터중 <br>
예측해야할 `count` 피쳐를 drop()함수를 사용하고, axis=1 옵션을 사용해 해당 열을 제외한 데이터들을 `X_train` 이라는 이름의 DataFrame 객체로 만들고 <br>
`count` 피쳐만을 데이터로 갖는 `Y_train` 이라는 이름의 DataFrame 객체로 만드는 코드를 아래에 작성하세요

In [10]:
X_train=train.drop('count',axis=1)
Y_train=pd.DataFrame(train['count'])
X_train

        id  hour  ...  hour_bef_pm10  hour_bef_pm2.5
0        3    20  ...           76.0            33.0
1        6    13  ...           73.0            40.0
2        7     6  ...           32.0            19.0
3        8    23  ...           75.0            64.0
4        9    18  ...           27.0            11.0
...    ...   ...  ...            ...             ...
1454  2174     4  ...           37.0            27.0
1455  2175     3  ...           34.0            19.0
1456  2176     5  ...           30.0            21.0
1457  2178    21  ...           71.0            36.0
1458  2179    17  ...           38.0            17.0

[1328 rows x 10 columns]

3. `model` 변수명으로 모델을 선언하고, fit() 함수를 사용해서, `X_train` 을 input 으로 삼고, `Y_train` 을 output 으로 삼아 모델을 훈련시키는 코드를 아래에 작성하세요

In [11]:
model= DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

4. predict() 를 이용해 test data 를 훈련된 모델로 예측한 data 를 생성하고 예측결과 상위 5개를 출력하는 코드를 작성하세요.

In [12]:
model.predict(test)[:5]

array([117., 305., 165.,  18.,  52.])

## 데이터 다운로드 2
---
아래 셀을 실행시켜 데이터를 colab 에 불러옵니다.
셀 실행은 Ctrl + Enter 를 이용해 실행시킬 수 있습니다.

In [13]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3i4n1QB'

import zipfile
with zipfile.ZipFile('3i4n1QB', 'r') as existing_zip:
    existing_zip.extractall('data')

--2021-10-11 09:44:04--  https://bit.ly/3i4n1QB
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw [following]
--2021-10-11 09:44:04--  https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw
Resolving drive.google.com (drive.google.com)... 172.217.203.139, 172.217.203.101, 172.217.203.102, ...
Connecting to drive.google.com (drive.google.com)|172.217.203.139|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/pdgkh49o91bq1vo6dge50o4hqs76aq77/1633945425000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download [following]
Warning: wildcards not supported in HTTP.
--2021-10-11 09:44:05--  https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/pdgkh49o91bq1vo6dge50o4hqs76aq77/1633945425000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download
Resolving doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)... 74.125.31.132, 2607:f8b0:400c:c02::84
Connecting to doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)|74.125.31.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137694 (134K) [application/zip]
Saving to: ‘3i4n1QB’

3i4n1QB             100%[===================>] 134.47K  --.-KB/s    in 0.001s

2021-10-11 09:44:05 (99.9 MB/s) - ‘3i4n1QB’ saved [137694/137694]

In [14]:
# 라이브러리 불러오기

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

In [16]:
train = pd.read_csv('data/train.csv')
train

      index  quality  fixed acidity  ...  sulphates  alcohol   type
0         0        5            5.6  ...       0.44     10.2  white
1         1        5            8.8  ...       0.59      9.5    red
2         2        5            7.9  ...       0.52     10.9  white
3         3        6            7.0  ...       0.50     10.8  white
4         4        6            7.8  ...       0.43     10.9  white
...     ...      ...            ...  ...        ...      ...    ...
5492   5492        5            7.7  ...       0.39     10.1  white
5493   5493        6            6.3  ...       0.51     11.0  white
5494   5494        7            7.8  ...       0.72     11.3  white
5495   5495        5            6.6  ...       0.41     10.5  white
5496   5496        6            7.0  ...       0.36      9.7  white

[5497 rows x 14 columns]

In [15]:
train = pd.read_csv('data/train.csv')

# Scailing
scaler = MinMaxScaler()
scaler.fit(train[['fixed acidity']])
train['Scaled fixed acidity'] = scaler.transform(train[['fixed acidity']])

# Encoding
encoder = OneHotEncoder()
encoder.fit(train[['type']])
onehot = encoder.transform(train[['type']])
onehot = onehot.toarray()
onehot = pd.DataFrame(onehot)
onehot.columns = encoder.get_feature_names()
train = pd.concat([train, onehot], axis = 1)
train = train.drop(columns = ['type'])
train.head()

   index  quality  fixed acidity  ...  Scaled fixed acidity  x0_red  x0_white
0      0        5            5.6  ...              0.148760     0.0       1.0
1      1        5            8.8  ...              0.413223     1.0       0.0
2      2        5            7.9  ...              0.338843     0.0       1.0
3      3        6            7.0  ...              0.264463     0.0       1.0
4      4        6            7.8  ...              0.330579     0.0       1.0

[5 rows x 16 columns]

5. sklearn에 model_selection 부분 속 KFold를 불러와보세요

In [17]:
from sklearn.model_selection import KFold

6. KFold에 n_splits = 5, shuffle = True, random_state = 0이라는 인자를 추가해 "kf"라는 변수에 저장해보세요

In [18]:
kf=KFold(n_splits = 5, shuffle = True, random_state = 0)

7. 반복문을 통해서 1번부터 5번까지의 데이터에 접근해보세요 (추가문제입니다. 꼭 풀 필요는 없되 답지를 참고해주세요.)

In [21]:
features=train.to_dict('series')
features

{'alcohol': 0       10.2
 1        9.5
 2       10.9
 3       10.8
 4       10.9
         ...
 5492    10.1
 5493    11.0
 5494    11.3
 5495    10.5
 5496     9.7
 Name: alcohol, Length: 5497, dtype: float64, 'chlorides': 0       0.042
 1       0.067
 2       0.057
 3       0.046
 4       0.059
         ...
 5492    0.029
 5493    0.034
 5494    0.035
 5495    0.042
 5496    0.049
 Name: chlorides, Length: 5497, dtype: float64, 'citric acid': 0       0.06
 1       0.14
 2       0.39
 3       0.31
 4       0.26
         ...
 5492    0.29
 5493    0.36
 5494    0.34
 5495    0.31
 5496    0.17
 Name: citric acid, Length: 5497, dtype: float64, 'density': 0       0.99432
 1       0.99690
 2       0.99176
 3       0.99390
 4       0.99550
          ...
 5492    0.99320
 5493    0.99074
 5494    0.99096
 5495    0.99195
 5496    0.99297
 Name: density, Length: 5497, dtype: float64, 'fixed acidity': 0       5.6
 1       8.8
 2       7.9
 3       7.0
 4       7.8
        ...
 5492    7.7
 5493    6.3
 5494    7.8
 5495    6.6
 5496    7.0
 Name: fixed acidity, Length: 5497, dtype: float64, 'free sulfur dioxide': 0        9.0
 1       10.0
 2       21.0
 3       29.0
 4       32.0
         ...
 5492    10.0
 5493    26.0
 5494    31.0
 5495    18.0
 5496     7.0
 Name: free sulfur dioxide, Length: 5497, dtype: float64, 'index': 0          0
 1          1
 2          2
 3          3
 4          4
         ...
 5492    5492
 5493    5493
 5494    5494
 5495    5495
 5496    5496
 Name: index, Length: 5497, dtype: int64, 'pH': 0       3.44
 1       3.19
 2       3.05
 3       3.26
 4       3.04
         ...
 5492    3.35
 5493    3.16
 5494    3.07
 5495    3.13
 5496    3.13
 Name: pH, Length: 5497, dtype: float64, 'quality': 0       5
 1       5
 2       5
 3       6
 4       6
        ..
 5492    5
 5493    6
 5494    7
 5495    5
 5496    6
 Name: quality, Length: 5497, dtype: int64, 'residual sugar': 0       6.8
 1       2.4
 2       2.0
 3       6.0
 4       9.5
        ...
 5492    1.3
 5493    1.2
 5494    1.1
 5495    1.6
 5496    1.1
 Name: residual sugar, Length: 5497, dtype: float64, 'sulphates': 0       0.44
 1       0.59
 2       0.52
 3       0.50
 4       0.43
         ...
 5492    0.39
 5493    0.51
 5494    0.72
 5495    0.41
 5496    0.36
 Name: sulphates, Length: 5497, dtype: float64, 'total sulfur dioxide': 0        84.0
 1        42.0
 2       138.0
 3       108.0
 4       178.0
         ...
 5492     64.0
 5493    111.0
 5494     93.0
 5495    101.0
 5496    119.0
 Name: total sulfur dioxide, Length: 5497, dtype: float64, 'type': 0       white
 1         red
 2       white
 3       white
 4       white
         ...
 5492    white
 5493    white
 5494    white
 5495    white
 5496    white
 Name: type, Length: 5497, dtype: object, 'volatile acidity': 0       0.695
 1       0.610
 2       0.210
 3       0.210
 4       0.400
         ...
 5492    0.150
 5493    0.180
 5494    0.150
 5495    0.410
 5496    0.350
 Name: volatile acidity, Length: 5497, dtype: float64}

In [25]:
pd.get_dummies(train)

      index  quality  fixed acidity  ...  alcohol  type_red  type_white
0         0        5            5.6  ...     10.2         0           1
1         1        5            8.8  ...      9.5         1           0
2         2        5            7.9  ...     10.9         0           1
3         3        6            7.0  ...     10.8         0           1
4         4        6            7.8  ...     10.9         0           1
...     ...      ...            ...  ...      ...       ...         ...
5492   5492        5            7.7  ...     10.1         0           1
5493   5493        6            6.3  ...     11.0         0           1
5494   5494        7            7.8  ...     11.3         0           1
5495   5495        5            6.6  ...     10.5         0           1
5496   5496        6            7.0  ...      9.7         0           1

[5497 rows x 15 columns]

In [22]:
from sklearn.datasets import load_iris 
iris=load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [23]:
n_iter=0

for train_index, test_index in kf.split(train):
  X_train, X_test= train[train_index],train[test_index]
  y_train, y_test= onehot[train_index],onehot[test_index]

  rfc.fit(X_train, y_train)
  pred= kf.predict(X_test)
  n_iter+=1

KeyError: ignored